// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePostM = "post"

// PostM Posts table
type PostM struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID    string    `gorm:"column:userID;not null;comment:User unique ID" json:"userID"`                                         // User unique ID
	PostID    string    `gorm:"column:postID;not null;uniqueIndex:idx_post_postID;comment:Post unique ID" json:"postID"`             // Post unique ID
	Title     string    `gorm:"column:title;not null;comment:Post title" json:"title"`                                               // Post title
	Content   string    `gorm:"column:content;not null;comment:Post content" json:"content"`                                         // Post content
	CreatedAt time.Time `gorm:"column:createdAt;not null;default:current_timestamp;comment:Post created time" json:"createdAt"`      // Post created time
	UpdatedAt time.Time `gorm:"column:updatedAt;not null;default:current_timestamp;comment:Post last updated time" json:"updatedAt"` // Post last updated time
}

// TableName PostM's table name
func (*PostM) TableName() string {
	return TableNamePostM
}
