// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserM = "user"

// UserM Users table
type UserM struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID    string    `gorm:"column:userID;not null;uniqueIndex:idx_user_userID;comment:User unique ID" json:"userID"`             // User unique ID
	Username  string    `gorm:"column:username;not null;uniqueIndex:idx_user_username;comment:Username (unique)" json:"username"`    // Username (unique)
	Password  string    `gorm:"column:password;not null;comment:User password (hashed)" json:"password"`                             // User password (hashed)
	Nickname  string    `gorm:"column:nickname;not null;comment:User nickname" json:"nickname"`                                      // User nickname
	Email     string    `gorm:"column:email;not null;comment:User email address" json:"email"`                                       // User email address
	Phone     string    `gorm:"column:phone;not null;uniqueIndex:idx_user_phone;comment:User phone number" json:"phone"`             // User phone number
	CreatedAt time.Time `gorm:"column:createdAt;not null;default:current_timestamp;comment:User created time" json:"createdAt"`      // User created time
	UpdatedAt time.Time `gorm:"column:updatedAt;not null;default:current_timestamp;comment:User last updated time" json:"updatedAt"` // User last updated time
}

// TableName UserM's table name
func (*UserM) TableName() string {
	return TableNameUserM
}
